// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.24.3
// source: minerva/v1/minerva.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// MineRvaClient is the client API for MineRva service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MineRvaClient interface {
	ParseSqlType(ctx context.Context, in *ParseSqlTypeRequest, opts ...grpc.CallOption) (*ParseSqlTypeReply, error)
}

type mineRvaClient struct {
	cc grpc.ClientConnInterface
}

func NewMineRvaClient(cc grpc.ClientConnInterface) MineRvaClient {
	return &mineRvaClient{cc}
}

func (c *mineRvaClient) ParseSqlType(ctx context.Context, in *ParseSqlTypeRequest, opts ...grpc.CallOption) (*ParseSqlTypeReply, error) {
	out := new(ParseSqlTypeReply)
	err := c.cc.Invoke(ctx, "/minerva.v1.MineRva/ParseSqlType", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MineRvaServer is the server API for MineRva service.
// All implementations must embed UnimplementedMineRvaServer
// for forward compatibility
type MineRvaServer interface {
	ParseSqlType(context.Context, *ParseSqlTypeRequest) (*ParseSqlTypeReply, error)
	mustEmbedUnimplementedMineRvaServer()
}

// UnimplementedMineRvaServer must be embedded to have forward compatible implementations.
type UnimplementedMineRvaServer struct {
}

func (UnimplementedMineRvaServer) ParseSqlType(context.Context, *ParseSqlTypeRequest) (*ParseSqlTypeReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ParseSqlType not implemented")
}
func (UnimplementedMineRvaServer) mustEmbedUnimplementedMineRvaServer() {}

// UnsafeMineRvaServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MineRvaServer will
// result in compilation errors.
type UnsafeMineRvaServer interface {
	mustEmbedUnimplementedMineRvaServer()
}

func RegisterMineRvaServer(s grpc.ServiceRegistrar, srv MineRvaServer) {
	s.RegisterService(&MineRva_ServiceDesc, srv)
}

func _MineRva_ParseSqlType_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ParseSqlTypeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MineRvaServer).ParseSqlType(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/minerva.v1.MineRva/ParseSqlType",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MineRvaServer).ParseSqlType(ctx, req.(*ParseSqlTypeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MineRva_ServiceDesc is the grpc.ServiceDesc for MineRva service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MineRva_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "minerva.v1.MineRva",
	HandlerType: (*MineRvaServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ParseSqlType",
			Handler:    _MineRva_ParseSqlType_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "minerva/v1/minerva.proto",
}
