// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: minerva/v1/minerva.proto

package v1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on ParseSqlTypeRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ParseSqlTypeRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ParseSqlTypeRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ParseSqlTypeRequestMultiError, or nil if none found.
func (m *ParseSqlTypeRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ParseSqlTypeRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if l := utf8.RuneCountInString(m.GetSql()); l < 5 || l > 1000000 {
		err := ParseSqlTypeRequestValidationError{
			field:  "Sql",
			reason: "value length must be between 5 and 1000000 runes, inclusive",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return ParseSqlTypeRequestMultiError(errors)
	}

	return nil
}

// ParseSqlTypeRequestMultiError is an error wrapping multiple validation
// errors returned by ParseSqlTypeRequest.ValidateAll() if the designated
// constraints aren't met.
type ParseSqlTypeRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ParseSqlTypeRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ParseSqlTypeRequestMultiError) AllErrors() []error { return m }

// ParseSqlTypeRequestValidationError is the validation error returned by
// ParseSqlTypeRequest.Validate if the designated constraints aren't met.
type ParseSqlTypeRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ParseSqlTypeRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ParseSqlTypeRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ParseSqlTypeRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ParseSqlTypeRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ParseSqlTypeRequestValidationError) ErrorName() string {
	return "ParseSqlTypeRequestValidationError"
}

// Error satisfies the builtin error interface
func (e ParseSqlTypeRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sParseSqlTypeRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ParseSqlTypeRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ParseSqlTypeRequestValidationError{}

// Validate checks the field values on ParseSqlTypeReply with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *ParseSqlTypeReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ParseSqlTypeReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ParseSqlTypeReplyMultiError, or nil if none found.
func (m *ParseSqlTypeReply) ValidateAll() error {
	return m.validate(true)
}

func (m *ParseSqlTypeReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Code

	// no validation rules for Message

	for idx, item := range m.GetData() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ParseSqlTypeReplyValidationError{
						field:  fmt.Sprintf("Data[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ParseSqlTypeReplyValidationError{
						field:  fmt.Sprintf("Data[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ParseSqlTypeReplyValidationError{
					field:  fmt.Sprintf("Data[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return ParseSqlTypeReplyMultiError(errors)
	}

	return nil
}

// ParseSqlTypeReplyMultiError is an error wrapping multiple validation errors
// returned by ParseSqlTypeReply.ValidateAll() if the designated constraints
// aren't met.
type ParseSqlTypeReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ParseSqlTypeReplyMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ParseSqlTypeReplyMultiError) AllErrors() []error { return m }

// ParseSqlTypeReplyValidationError is the validation error returned by
// ParseSqlTypeReply.Validate if the designated constraints aren't met.
type ParseSqlTypeReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ParseSqlTypeReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ParseSqlTypeReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ParseSqlTypeReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ParseSqlTypeReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ParseSqlTypeReplyValidationError) ErrorName() string {
	return "ParseSqlTypeReplyValidationError"
}

// Error satisfies the builtin error interface
func (e ParseSqlTypeReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sParseSqlTypeReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ParseSqlTypeReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ParseSqlTypeReplyValidationError{}

// Validate checks the field values on ParseSqlTypeReply_SqlCheckResult with
// the rules defined in the proto definition for this message. If any rules
// are violated, the first error encountered is returned, or nil if there are
// no violations.
func (m *ParseSqlTypeReply_SqlCheckResult) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ParseSqlTypeReply_SqlCheckResult with
// the rules defined in the proto definition for this message. If any rules
// are violated, the result is a list of violation errors wrapped in
// ParseSqlTypeReply_SqlCheckResultMultiError, or nil if none found.
func (m *ParseSqlTypeReply_SqlCheckResult) ValidateAll() error {
	return m.validate(true)
}

func (m *ParseSqlTypeReply_SqlCheckResult) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Sql

	// no validation rules for Risk

	if len(errors) > 0 {
		return ParseSqlTypeReply_SqlCheckResultMultiError(errors)
	}

	return nil
}

// ParseSqlTypeReply_SqlCheckResultMultiError is an error wrapping multiple
// validation errors returned by
// ParseSqlTypeReply_SqlCheckResult.ValidateAll() if the designated
// constraints aren't met.
type ParseSqlTypeReply_SqlCheckResultMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ParseSqlTypeReply_SqlCheckResultMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ParseSqlTypeReply_SqlCheckResultMultiError) AllErrors() []error { return m }

// ParseSqlTypeReply_SqlCheckResultValidationError is the validation error
// returned by ParseSqlTypeReply_SqlCheckResult.Validate if the designated
// constraints aren't met.
type ParseSqlTypeReply_SqlCheckResultValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ParseSqlTypeReply_SqlCheckResultValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ParseSqlTypeReply_SqlCheckResultValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ParseSqlTypeReply_SqlCheckResultValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ParseSqlTypeReply_SqlCheckResultValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ParseSqlTypeReply_SqlCheckResultValidationError) ErrorName() string {
	return "ParseSqlTypeReply_SqlCheckResultValidationError"
}

// Error satisfies the builtin error interface
func (e ParseSqlTypeReply_SqlCheckResultValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sParseSqlTypeReply_SqlCheckResult.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ParseSqlTypeReply_SqlCheckResultValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ParseSqlTypeReply_SqlCheckResultValidationError{}
